name: my_app
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: 1.2.1
  logging: ^1.2.0
  get_it: ^7.7.0
  bot_toast: ^4.1.3
  freezed_annotation: ^2.4.1
  meta: ^1.11.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2



flutter:
  uses-material-design: true
  generate: true
