name: my_app
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  http: any
  logging: ^1.2.0
  get_it: ^7.6.6
  bot_toast: ^4.1.3
  freezed_annotation: ^2.4.1
  meta: ^1.3.3

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.6



flutter:
  uses-material-design: true
  generate: true
